"""Closing note about how the block is produced."""

from __future__ import annotations

from . import Context


def render(ctx: Context) -> list[str]:
    return [
        "_Refreshed hourly by [update-profile.yml](.github/workflows/update-profile.yml) "
        "— generated by [`scripts/refresh.py`](scripts/refresh.py), GitHub-native, "
        "no third party services. Public data only._"
    ]
